include:
  - { project: Jean.M.Girard/devops/templates, file: tasks/terraform.yml, ref: develop }


stages:
  - validate
  - build
  - test
  - deploy

validate:
  stage: validate
  extends: [.terraform:validate]

#validate:
#  stage: validate
#  extends: [.terraform:validate]
#
#lint:
#  stage: validate
#  extends: [.terraform:lint]


upload:
  extends: [.terraform:upload]
  stage: deploy
  variables:
    TERRAFORM_MODULE_DIR: '${CI_PROJECT_DIR}'
    TERRAFORM_MODULE_NAME: agnostic-dns
    TERRAFORM_MODULE_SYSTEM: local
    TERRAFORM_MODULE_VERSION: '${CI_COMMIT_TAG}'
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v([0-9|\.]+)/'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
      allow_failure: true
