version: "3"

tasks:
  default:
    deps: [format, docs]

  format:
    summary: Format Terraform files
    desc: Format Terraform files
    silent: true
    cmd: terraform fmt  -recursive -write=true

  docs:
    summary: Update Terraform docs
    desc: Update Terraform docs
    silent: true
    cmd: "find . -type f -name main.tf | while read file; do DIR=\"$(dirname $file)\"; \n
      { terraform-docs markdown table --output-file README.md --output-mode inject \"$DIR\"; } || { echo \"Failed to update: $DIR\";  } \n
      done"
