# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
#
# DO NOT EDIT THIS FILE
#

variable "meta" {
  type    = any
  default = {}
}
module "meta" {
  source = "git::ssh://git@gitlab.com/Jean.M.Girard/libs/terraform/meta.git"
  meta   = var.meta
}
locals {
  meta            = { for k, v in module.meta : k => v if v != null && v != "" }
  env             = lookup(local.meta, "env", "")
  environment     = lookup(local.meta, "environment", "")
  region          = lookup(local.meta, "region", "")
  region_code     = lookup(local.meta, "region_code", "")
  location        = lookup(local.meta, "location", "eastus")
  location_global = lookup(local.meta, "location_global", lookup(local.meta, "location", "eastus"))
  location_name   = lookup(local.meta, "location_name", lookup(local.meta, "location", "Us.East"))
  ns              = lookup(local.meta, "ns", "")
  stack           = lookup(local.meta, "stack", "")
  component       = lookup(local.meta, "component", "")
  tags            = lookup(local.meta, "tags", {})
  default_tags    = lookup(local.meta, "default_tags", {})
  all_tags        = lookup(local.meta, "all_tags", merge(local.default_tags, local.tags))
}

output "meta" {
  value       = local.meta
  description = "Metadata"
}
